name: Sync Fork with Upstream

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add upstream https://github.com/numowork/real-time-chat.git
          git fetch upstream
          git checkout master 
          git merge upstream/master --no-edit 
          git push
